version: '3.9'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./volume/mysql:/var/lib/mysql
    

  practica-books_monolith:
    image: practica-books_monolith
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/books?createDatabaseIfNotExist=true
      - APP.ARCHITECTURE.MODEL=USERS_IN_MONOLITH
    container_name: 'practica-books_monolith'
    restart: on-failure
    build: 
      context: ./practica-books_monolith
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8081
    depends_on:
      - db

  practica-books_ms:
    image: practica-books_ms
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/books_ms?createDatabaseIfNotExist=true
    container_name: 'practica-books_ms'
    restart: on-failure
    build: 
      context: ./practica-books_ms
      dockerfile: ./Dockerfile
    ports: 
      - 8082:8082
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/conf.d/default.conf